# Test 1
#
# Single box with VirtualBox provider.
#
# NOTE: Make sure you have the trusty64 base box installed...
# vagrant box add trusty64 https://atlas.hashicorp.com/ubuntu/boxes/trusty64/versions/14.04/providers/virtualbox.box

Vagrant.configure("2") do |config|
  config.vm.box = "trusty64"
  config.vm.hostname = "mytrusty.box"
  config.vm.network :private_network, ip: "10.1.1.70"
  config.vm.synced_folder "../../test1-folder", "/var/www/html/test1-folder",
           id: "test1-folder", type: "nfs", :nfs => { :mount_options => ["dmode=777","fmode=777"] }
  config.vm.provision "shell", path: "bootstrap.sh"

  config.vm.define :test1 do |vmconfig|
    vmconfig.vm.provider :virtualbox do |vb|
      vb.name = "test1"
      vb.customize [
        "modifyvm", :id,
        "--cpuexecutioncap", "50",
        "--memory", "512",
      ]
    end
  end
end
