# For deep-skies.com
#
# Single box with VirtualBox provider.
#
# NOTES:
# - Make sure you have the trusty64 base box installed:
#   vagrant box add trusty64 https://atlas.hashicorp.com/ubuntu/boxes/trusty64/versions/14.04/providers/virtualbox.box
# - create the the "Deep-Skies-Symfony" folder (clone the repo) - two folders above this one.

Vagrant.configure("2") do |config|
  config.vm.box = "trusty64"
  config.vm.hostname = "dso-dev.box"
  config.vm.network :private_network, ip: "10.1.1.7"
  config.vm.synced_folder "../../Deep-Skies-Symfony", "/var/www/html/Deep-Skies-Symfony",
             id: "Deep-Skies-Symfony", type: "nfs", :nfs => { :mount_options => ["dmode=777","fmode=777"] }
  config.vm.provision :shell, path: "bootstrap.sh"

  # @see: https://github.com/mitchellh/vagrant/issues/1673
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  config.vm.define :dso_dev do |vmconfig|
    vmconfig.vm.provider :virtualbox do |vb|
      vb.name = "DSO Dev"
      vb.customize [
        "modifyvm", :id,
        "--cpuexecutioncap", "50",
        "--memory", "2048",
      ]
    end
  end
end
