# For deep-skies.com
#
# Single box with VirtualBox provider.
#
# NOTES:
# - Make sure you have the trusty64 base box installed...
#   vagrant box add trusty64 https://atlas.hashicorp.com/ubuntu/boxes/trusty64/versions/14.04/providers/virtualbox.box
# - create the the "Deep-Skies-Symfony" (clone the repo) - two folders above this one.

Vagrant.configure("2") do |config|
  config.vm.box = "trusty64"
  config.vm.hostname = "dso-dev.box"
  config.vm.network :private_network, ip: "192.168.0.40"
  config.vm.synced_folder "../../Deep-Skies-Symfony", "/var/www/Deep-Skies-Symfony",
             id: "Deep-Skies-Symfony", type: "nfs", :nfs => { :mount_options => ["dmode=777","fmode=777"] }

  config.vm.define :dso_dev do |vmconfig|
    vmconfig.vm.provider :virtualbox do |vb|
      vb.name = "DSO Dev"
      vb.customize [
        "modifyvm", :id,
        "--cpuexecutioncap", "50",
        "--memory", "1024",
      ]
    end
  end
end
